version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=development
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: "redis:alpine"
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
